language: cpp     # 指定项目语言类型
dist: trusty
sudo: false       # 是否需要 sudo 权限
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

branches:
  only:
  - master

before_install:
    - eval "${MATRIX_EVAL}"

script:           # 构建的命令，默认为 ./configure && make
  - cd ./grad3
  - make unit_test
  - make clean
  - make static
